name: Build and Test

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - main
    - feature/*

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      run: nuget restore ExpenseManagerApp.sln
    - name: Build Solution
      run: msbuild ExpenseManagerApp.sln /p:configuration="Release"
    - name: Run Unit Tests
      run: vstest.console.exe .\UnitTests\bin\Release\net6.0-windows\UnitTests.dll
    - name: Run BDD Tests
      run: vstest.console.exe .\BDDTests\bin\Release\net6.0-windows\BDDTests.dll
